### ISSUE TITLE
This plugin does not work

### ISSUE THREAD

**Issue by Lazarus132** [archielite/botble-url-redirector#3]
There is no error message, but I can describe the problem to you.
First of all, no matter which url it is, there is always a red cross on the right side of the field of the original URL* when you click on save, the saved page is displayed after the reload, but a redirect does not take place when you call up the url. Please fix this.
<img width="771" alt="Screenshot 2024-01-14 133116" src="https://github.com/archielite/botble-url-redirector/assets/78088157/3e66fa88-4820-47f1-b07b-cf25844a06c5">

**Comment by dinhquochan** [comment]
Thank you for reporting. We will fix it ASAP!

**Comment by Lazarus132** [comment]
When can I expect to receive an update?

**Comment by dinhquochan** [comment]
Fixed in v2.0.1
